export const DIFFICULTY_PRESETS = Object.freeze({
  easy: Object.freeze({
    id: 'easy', playerHull: 135, countermeasures: 20, incomingDamage: .72,
    enemyHealth: .82, enemyAimSpread: 1.35, wingmanDamage: 1.15, wingmanAimSpread: .9,
    enemyOpeningDelayScale: .62, enemyPassRangeScale: .88,
    enemyGunMaxRange: 2050, enemyGunBoresight: .89, enemyGunCooldown: 2.05,
    enemyGunCooldownJitter: 1.15, enemyGunBurstMin: 4, enemyGunBurstMax: 6,
    enemyGunBurstInterval: .11, enemyAttackTurnRate: .32,
    enemyDefensiveTurnRate: .54, enemyDefensivePitchRate: .25,
    enemyLockEvasionChance: .18, enemyLockCountermeasureChance: .48,
    enemyLockEvasionDuration: 2.5, enemyMissileEvasionDuration: 3.2,
    enemyLockCountermeasureFollowupChance: 0,
    enemyCountermeasureCapacity: 2, enemyCountermeasureCooldown: 5.8,
    enemyTacticalManeuverCooldown: 17, enemyTacticalManeuverJitter: 9,
    enemyTacticalManeuverChance: .24, enemyTacticalManeuverRange: 5200,
    enemyEvasiveClimbMin: 120, enemyEvasiveClimbMax: 320,
    enemyAirPriorityRange: 8000, enemyGroundStrafeRange: 5200,
    enemyGroundStrafeChance: .05, enemyGroundStrafeCooldown: 20,
    enemyMissileCapacity: 1, enemyMissileInitialDelay: 9, enemyMissileCooldown: 19,
    enemyMissileCooldownJitter: 5, enemyMissileMinRange: 3400, enemyMissileMaxRange: 5700,
    enemyMissileBoresight: .95, hostileMissileSpeed: 335, hostileMissileTurnRate: 1.1,
    enemyAaInitialDelay: 3.4, enemyAaInitialJitter: 3.6,
    enemyAaMaxRange: 1700, enemyAaCooldown: 10.5, enemyAaCooldownJitter: 4.5,
    enemyAaBurstRounds: 3, enemyAaBurstInterval: .18,
  }),
  standard: Object.freeze({
    id: 'standard', playerHull: 100, countermeasures: 20, incomingDamage: 1,
    enemyHealth: 1, enemyAimSpread: 1, wingmanDamage: 1, wingmanAimSpread: 1,
    enemyOpeningDelayScale: .44, enemyPassRangeScale: 1.12,
    enemyGunMaxRange: 2700, enemyGunBoresight: .78, enemyGunCooldown: 1.05,
    enemyGunCooldownJitter: .78, enemyGunBurstMin: 7, enemyGunBurstMax: 10,
    enemyGunBurstInterval: .085, enemyAttackTurnRate: .42,
    enemyDefensiveTurnRate: .61, enemyDefensivePitchRate: .29,
    enemyLockEvasionChance: .38, enemyLockCountermeasureChance: .68,
    enemyLockEvasionDuration: 3, enemyMissileEvasionDuration: 3.6,
    enemyLockCountermeasureFollowupChance: .18,
    enemyCountermeasureCapacity: 4, enemyCountermeasureCooldown: 3.8,
    enemyTacticalManeuverCooldown: 10, enemyTacticalManeuverJitter: 5,
    enemyTacticalManeuverChance: .58, enemyTacticalManeuverRange: 7200,
    enemyEvasiveClimbMin: 420, enemyEvasiveClimbMax: 820,
    enemyAirPriorityRange: 9000, enemyGroundStrafeRange: 6600,
    enemyGroundStrafeChance: .16, enemyGroundStrafeCooldown: 14,
    enemyMissileCapacity: 2, enemyMissileInitialDelay: 7, enemyMissileCooldown: 14,
    enemyMissileCooldownJitter: 5, enemyMissileMinRange: 3000, enemyMissileMaxRange: 6400,
    enemyMissileBoresight: .93, hostileMissileSpeed: 380, hostileMissileTurnRate: 1.36,
    enemyAaInitialDelay: 2, enemyAaInitialJitter: 2.6,
    enemyAaMaxRange: 1950, enemyAaCooldown: 7.2, enemyAaCooldownJitter: 3.8,
    enemyAaBurstRounds: 4, enemyAaBurstInterval: .14,
  }),
  hard: Object.freeze({
    id: 'hard', playerHull: 88, countermeasures: 20, incomingDamage: 1.25,
    enemyHealth: 1.16, enemyAimSpread: .68, wingmanDamage: .9, wingmanAimSpread: 1.1,
    enemyOpeningDelayScale: .22, enemyPassRangeScale: 1.32,
    enemyGunMaxRange: 3100, enemyGunBoresight: .68, enemyGunCooldown: .62,
    enemyGunCooldownJitter: .42, enemyGunBurstMin: 10, enemyGunBurstMax: 14,
    enemyGunBurstInterval: .07, enemyAttackTurnRate: .54,
    enemyDefensiveTurnRate: .82, enemyDefensivePitchRate: .4,
    enemyLockEvasionChance: .72, enemyLockCountermeasureChance: .92,
    enemyLockEvasionDuration: 3.5, enemyMissileEvasionDuration: 4.1,
    enemyLockCountermeasureFollowupChance: .68,
    enemyCountermeasureCapacity: 6, enemyCountermeasureCooldown: 2.3,
    enemyTacticalManeuverCooldown: 5.2, enemyTacticalManeuverJitter: 2.8,
    enemyTacticalManeuverChance: .9, enemyTacticalManeuverRange: 8600,
    enemyEvasiveClimbMin: 850, enemyEvasiveClimbMax: 1550,
    enemyAirPriorityRange: 10500, enemyGroundStrafeRange: 7600,
    enemyGroundStrafeChance: .3, enemyGroundStrafeCooldown: 10,
    enemyMissileCapacity: 3, enemyMissileInitialDelay: 3.2, enemyMissileCooldown: 8,
    enemyMissileCooldownJitter: 3, enemyMissileMinRange: 2400, enemyMissileMaxRange: 8200,
    enemyMissileBoresight: .78, hostileMissileSpeed: 430, hostileMissileTurnRate: 1.55,
    enemyAaInitialDelay: .9, enemyAaInitialJitter: 1.7,
    enemyAaMaxRange: 2200, enemyAaCooldown: 5.2, enemyAaCooldownJitter: 2.6,
    enemyAaBurstRounds: 5, enemyAaBurstInterval: .11,
  }),
});

export function getDifficultyPreset(id = 'standard') {
  return DIFFICULTY_PRESETS[id] ?? DIFFICULTY_PRESETS.standard;
}
