export const DIFFICULTY_PRESETS = Object.freeze({
  easy: Object.freeze({
    id: 'easy', playerHull: 135, countermeasures: 20, incomingDamage: .72,
    enemyHealth: .82, enemyAimSpread: 1.35, wingmanDamage: 1.15, wingmanAimSpread: .9,
    enemyOpeningDelayScale: .62, enemyPassRangeScale: .88,
    enemyDetectionRange: 5400, enemyDetectionReactionDelay: 6.5,
    enemyGunMaxRange: 2300, enemyGunBoresight: .84, enemyGunLeadTime: 3.5, enemyGunCooldown: 1.7,
    enemyGunCooldownJitter: .9, enemyGunBurstMin: 5, enemyGunBurstMax: 8,
    enemyGunBurstInterval: .11, enemyAttackTurnRate: .32,
    enemyDefensiveTurnRate: .54, enemyDefensivePitchRate: .25,
    enemyLockEvasionChance: .18, enemyLockCountermeasureChance: .48,
    enemyLockEvasionDuration: 2.5, enemyMissileEvasionDuration: 3.2,
    enemyLockCountermeasureFollowupChance: 0,
    enemyCountermeasureCapacity: 2, enemyCountermeasureCooldown: 5.8,
    enemyTacticalManeuverCooldown: 17, enemyTacticalManeuverJitter: 9,
    enemyTacticalManeuverChance: .24, enemyTacticalManeuverRange: 5200,
    enemyEvasiveClimbMin: 120, enemyEvasiveClimbMax: 320,
    enemyAirPriorityRange: 8000, enemyGroundStrafeRange: 5200,
    enemyGroundStrafeChance: .05, enemyGroundStrafeCooldown: 20,
    enemyMissileCapacity: 1, enemyMissileInitialDelay: 9, enemyMissileCooldown: 19,
    enemyMissileCooldownJitter: 5, enemyMissileMinRange: 3400, enemyMissileMaxRange: 5700,
    enemyMissileBoresight: .95, hostileMissileSpeed: 335, hostileMissileTurnRate: 1.1,
    hostileMissileDamage: 44, hostileMissileProximityRadius: 16,
    wingmanAirMissileCapacity: 2, wingmanAirMissileCooldown: 6.5,
    wingmanAirMissileMinRange: 2600, wingmanAirMissileMaxRange: 6900,
    enemyAaInitialDelay: 4.2, enemyAaInitialJitter: 3.2,
    enemyAaMaxRange: 2100, enemyAaCooldown: 8.2, enemyAaCooldownJitter: 3,
    enemyAaBurstRounds: 2, enemyAaBurstInterval: .15,
    enemyAaBurstScale: .42, enemyAaDispersionScale: 1.9, enemyAaAltitudeScale: .72,
    enemyAaDamageMultiplier: .58, enemyAaStopToFireChance: .2,
    enemyAaT72StopToFireChance: .48,
  }),
  standard: Object.freeze({
    id: 'standard', playerHull: 100, countermeasures: 20, incomingDamage: 1,
    enemyHealth: 1, enemyAimSpread: 1, wingmanDamage: 1, wingmanAimSpread: 1,
    enemyOpeningDelayScale: .44, enemyPassRangeScale: 1.12,
    enemyDetectionRange: 6100, enemyDetectionReactionDelay: 4,
    enemyGunMaxRange: 3000, enemyGunBoresight: .72, enemyGunCooldown: .82,
    enemyGunCooldownJitter: .55, enemyGunBurstMin: 8, enemyGunBurstMax: 12,
    enemyGunBurstInterval: .075, enemyAttackTurnRate: .42,
    enemyDefensiveTurnRate: .61, enemyDefensivePitchRate: .29,
    enemyLockEvasionChance: .38, enemyLockCountermeasureChance: .68,
    enemyLockEvasionDuration: 3, enemyMissileEvasionDuration: 3.6,
    enemyLockCountermeasureFollowupChance: .18,
    enemyCountermeasureCapacity: 4, enemyCountermeasureCooldown: 3.8,
    enemyTacticalManeuverCooldown: 10, enemyTacticalManeuverJitter: 5,
    enemyTacticalManeuverChance: .58, enemyTacticalManeuverRange: 7200,
    enemyEvasiveClimbMin: 420, enemyEvasiveClimbMax: 820,
    enemyAirPriorityRange: 9000, enemyGroundStrafeRange: 6600,
    enemyGroundStrafeChance: .16, enemyGroundStrafeCooldown: 14,
    enemyMissileCapacity: 3, enemyMissileInitialDelay: 5.5, enemyMissileCooldown: 10.5,
    enemyMissileCooldownJitter: 2.8, enemyMissileMinRange: 2200, enemyMissileMaxRange: 6500,
    enemyMissileBoresight: .88, hostileMissileSpeed: 395, hostileMissileTurnRate: 1.55,
    hostileMissileBurnTime: 10, hostileMissileLife: 16, hostileMissileCoastDrag: .075,
    hostileMissileDamage: 58, hostileMissileProximityRadius: 27,
    wingmanAirMissileCapacity: 3, wingmanAirMissileCooldown: 5.2,
    wingmanAirMissileMinRange: 2300, wingmanAirMissileMaxRange: 7800,
    enemyAaInitialDelay: 2, enemyAaInitialJitter: 2,
    enemyAaMaxRange: 2650, enemyAaCooldown: 5.5, enemyAaCooldownJitter: 2,
    enemyAaBurstRounds: 3, enemyAaBurstInterval: .11,
    enemyAaBurstScale: .72, enemyAaDispersionScale: 1.45, enemyAaAltitudeScale: .9,
    enemyAaDamageMultiplier: .88, enemyAaStopToFireChance: .4,
    enemyAaT72StopToFireChance: .68,
  }),
  hard: Object.freeze({
    id: 'hard', playerHull: 88, countermeasures: 20, incomingDamage: 1.25,
    enemyHealth: 1.16, enemyAimSpread: .68, wingmanDamage: .9, wingmanAimSpread: 1.1,
    enemyOpeningDelayScale: .22, enemyPassRangeScale: 1.32,
    enemyDetectionRange: 6700, enemyDetectionReactionDelay: 1.8,
    enemyGunMaxRange: 3500, enemyGunBoresight: .58, enemyGunLeadTime: 6.2, enemyGunCooldown: .42,
    enemyGunCooldownJitter: .28, enemyGunBurstMin: 14, enemyGunBurstMax: 18,
    enemyGunBurstInterval: .055, enemyAttackTurnRate: .54,
    enemyDefensiveTurnRate: .82, enemyDefensivePitchRate: .4,
    enemyLockEvasionChance: .72, enemyLockCountermeasureChance: .92,
    enemyLockEvasionDuration: 3.5, enemyMissileEvasionDuration: 4.1,
    enemyLockCountermeasureFollowupChance: .68,
    enemyCountermeasureCapacity: 6, enemyCountermeasureCooldown: 2.3,
    enemyTacticalManeuverCooldown: 5.2, enemyTacticalManeuverJitter: 2.8,
    enemyTacticalManeuverChance: .9, enemyTacticalManeuverRange: 8600,
    enemyEvasiveClimbMin: 850, enemyEvasiveClimbMax: 1550,
    enemyAirPriorityRange: 10500, enemyGroundStrafeRange: 7600,
    enemyGroundStrafeChance: .3, enemyGroundStrafeCooldown: 10,
    enemyMissileCapacity: 5, enemyMissileInitialDelay: 1.6, enemyMissileCooldown: 4.4,
    enemyMissileCooldownJitter: 1.1, enemyMissileMinRange: 1500, enemyMissileMaxRange: 7200,
    enemyMissileBoresight: .68, hostileMissileSpeed: 475, hostileMissileTurnRate: 2.15,
    hostileMissileBurnTime: 11, hostileMissileLife: 17, hostileMissileCoastDrag: .045,
    hostileMissileDamage: 67, hostileMissileProximityRadius: 36,
    wingmanAirMissileCapacity: 4, wingmanAirMissileCooldown: 4.1,
    wingmanAirMissileMinRange: 1900, wingmanAirMissileMaxRange: 8500,
    enemyAaInitialDelay: .9, enemyAaInitialJitter: 1.4,
    enemyAaMaxRange: 3000, enemyAaCooldown: 3.4, enemyAaCooldownJitter: 1.1,
    enemyAaBurstRounds: 4, enemyAaBurstInterval: .085,
    enemyAaBurstScale: .94, enemyAaDispersionScale: 1.16, enemyAaAltitudeScale: 1,
    enemyAaDamageMultiplier: 1.12, enemyAaStopToFireChance: .54,
    enemyAaT72StopToFireChance: .82,
  }),
});

export function getDifficultyPreset(id = 'standard') {
  return DIFFICULTY_PRESETS[id] ?? DIFFICULTY_PRESETS.standard;
}
