export const MISSIONS = {
  intercept: {
    id: 'intercept',
    unlocks: ['support'],
    deferredHostiles: true,
    navigationDistance: 3600,
    navigationRadius: 850,
    departureDuration: 4,
    hostiles: 4,
    hostileSpawnDistance: 7300,
    hostileLateralSpacing: 580,
    openingDelay: 16,
    wingmen: 2,
    groundBattle: true,
    groundPairs: 6,
    groundTrucks: 12,
    groundFrontSpan: 11800,
    convoyArea: 11600,
    objective: { type: 'clearAir' },
  },
  patrol: {
    id: 'patrol',
    unlocks: ['intercept'],
    deferredHostiles: true,
    navigationDistance: 4200,
    navigationRadius: 850,
    departureDuration: 4,
    hostiles: 2,
    hostileSpawnDistance: 7300,
    hostileLateralSpacing: 680,
    openingDelay: 24,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    objective: { type: 'clearAir' },
  },
  support: {
    id: 'support',
    unlocks: [],
    deferredHostiles: true,
    navigationDistance: 3500,
    navigationRadius: 850,
    departureDuration: 4,
    hostiles: 1,
    hostileSpawnDistance: 7100,
    openingDelay: 19,
    wingmen: 2,
    groundBattle: true,
    groundPairs: 6,
    groundTrucks: 12,
    groundFrontSpan: 10400,
    convoyArea: 9800,
    objective: { type: 'support' },
  },
  training: {
    id: 'training',
    unlocks: [],
    deferredHostiles: true,
    navigationDistance: 3200,
    navigationRadius: 850,
    departureDuration: 3,
    hostiles: 0,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    objective: { type: 'training', duration: 90 },
  },
};
