export const MISSIONS = {
  intercept: {
    id: 'intercept',
    hostiles: 4,
    hostileSpawnDistance: 7300,
    hostileLateralSpacing: 580,
    wingmen: 2,
    groundBattle: true,
    groundPairs: 6,
    groundTrucks: 12,
    objective: { type: 'clearAir' },
  },
  patrol: {
    id: 'patrol',
    hostiles: 2,
    hostileSpawnDistance: 7300,
    hostileLateralSpacing: 680,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    objective: { type: 'clearAir' },
  },
  support: {
    id: 'support',
    hostiles: 1,
    hostileSpawnDistance: 7100,
    wingmen: 2,
    groundBattle: true,
    groundPairs: 6,
    groundTrucks: 12,
    objective: { type: 'support' },
  },
  training: {
    id: 'training',
    hostiles: 0,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    objective: { type: 'training', duration: 90 },
  },
};
