export const MISSIONS = {
  intercept: {
    id: 'intercept',
    unlocks: ['support'],
    deferredHostiles: true,
    navigationDistance: 5000,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 4,
    hostileSpawnDistance: 15500,
    hostileMinimumSpawnDistance: 14000,
    hostileStagingDistance: 6500,
    hostileLateralSpacing: 1250,
    openingDelay: 16,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    groundIto90Count: 0,
    groundShilkaCount: 0,
    objective: { type: 'clearAir' },
    optionalObjectives: [
      { id: 'wingmen-home', type: 'allWingmenSurvive' },
      { id: 'lead-intercept', type: 'interceptBeforeZone', target: {
        collection: 'airHostiles', index: 0, labelKey: 'mission.optionalTarget.leadFighter',
      }, zoneRadius: 7200 },
      { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 300 },
    ],
    variants: [
      {
        id: 'long-range-screen', labelKey: 'mission.variant.intercept.longRange', weight: 3,
        changes: { hostileComposition: ['su27', 'mig29', 'su27', 'mig29'] },
        reinforcement: {
          probability: .12, delaySeconds: 70, hostiles: 1, composition: ['mig29'],
          spawnDistance: 11800, minimumSpawnDistance: 10400, lateralSpacing: 700, entry: 'scramble',
        },
      },
      {
        id: 'rapid-scramble', labelKey: 'mission.variant.intercept.rapidScramble', weight: 1,
        changes: {
          hostiles: 5,
          hostileComposition: ['mig29', 'su27', 'mig29', 'su27', 'mig29'],
          hostileSpawnDistance: 13200,
          hostileMinimumSpawnDistance: 11800,
          hostileLateralSpacing: 1500,
          hostileEntry: 'scramble',
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'lead-intercept', type: 'interceptBeforeZone', target: {
              collection: 'airHostiles', index: 0, labelKey: 'mission.optionalTarget.leadFighter',
            }, zoneRadius: 7600 },
            { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 330 },
          ],
        },
        reinforcement: {
          probability: .24, delaySeconds: 65, hostiles: 1, composition: ['su27'],
          spawnDistance: 12000, minimumSpawnDistance: 10600, lateralSpacing: 700, entry: 'scramble',
        },
      },
    ],
  },
  patrol: {
    id: 'patrol',
    unlocks: ['intercept'],
    deferredHostiles: true,
    navigationDistance: 5000,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 2,
    hostileSpawnDistance: 15500,
    hostileMinimumSpawnDistance: 14000,
    hostileStagingDistance: 6500,
    hostileLateralSpacing: 1450,
    openingDelay: 24,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    objective: { type: 'clearAir' },
    optionalObjectives: [
      { id: 'wingmen-home', type: 'allWingmenSurvive' },
      { id: 'no-damage', type: 'noDamage' },
      { id: 'missile-reserve', type: 'preserveMissiles', minimumRemaining: 16 },
    ],
    variants: [
      {
        id: 'routine-patrol', labelKey: 'mission.variant.patrol.routine', weight: 3,
        changes: { hostileComposition: ['su27', 'mig29'] },
        reinforcement: {
          probability: .18, delaySeconds: 62, hostiles: 1, composition: ['mig29'],
          spawnDistance: 12200, minimumSpawnDistance: 10800, lateralSpacing: 700, entry: 'scramble',
        },
      },
      {
        id: 'border-scramble', labelKey: 'mission.variant.patrol.borderScramble', weight: 1,
        changes: {
          hostiles: 3,
          hostileComposition: ['mig29', 'su27', 'mig29'],
          hostileSpawnDistance: 14000,
          hostileMinimumSpawnDistance: 12500,
          hostileLateralSpacing: 1750,
          hostileEntry: 'scramble',
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'no-damage', type: 'noDamage' },
            { id: 'missile-reserve', type: 'preserveMissiles', minimumRemaining: 15 },
          ],
        },
        reinforcement: {
          probability: .22, delaySeconds: 58, hostiles: 1, composition: ['su27'],
          spawnDistance: 12400, minimumSpawnDistance: 11000, lateralSpacing: 700, entry: 'scramble',
        },
      },
    ],
  },
  support: {
    id: 'support',
    unlocks: [],
    deferredHostiles: true,
    navigationDistance: 5000,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 1,
    hostileSpawnDistance: 15500,
    hostileMinimumSpawnDistance: 14000,
    hostileStagingDistance: 6500,
    openingDelay: 19,
    wingmen: 2,
    groundBattle: true,
    groundPairs: 9,
    groundTrucks: 16,
    groundFriendlyTrucks: 6,
    groundFrontSpan: 27000,
    convoyArea: 24000,
    hostileHelicopters: 2,
    hostileHelicopterSpawnDistance: 13000,
    hostileHelicopterMinimumSpawnDistance: 11000,
    hostileHelicopterLateralSpacing: 1400,
    hostileHelicopterSpawnAltitude: 520,
    groundIto90Count: 2,
    groundShilkaCount: 2,
    battlefieldIngressOffset: 5000,
    objective: { type: 'support' },
    optionalObjectives: [
      { id: 'wingmen-home', type: 'allWingmenSurvive' },
      { id: 'destroy-logistics', type: 'destroyOptionalGroundTarget', target: {
        collection: 'groundHostiles', role: 'logistics',
        labelKey: 'mission.optionalTarget.hostileLogistics',
      } },
      { id: 'protect-friendly', type: 'protectFriendlyGroundUnit', target: {
        collection: 'friendlyGround', role: 'defender',
        labelKey: 'mission.optionalTarget.friendlyArmor',
      } },
      { id: 'missile-reserve', type: 'preserveMissiles', minimumRemaining: 12 },
    ],
    variants: [
      {
        id: 'armored-push', labelKey: 'mission.variant.support.armoredPush', weight: 3,
        changes: {},
        reinforcement: {
          probability: .14, delaySeconds: 78, hostiles: 1, composition: ['mig29'],
          spawnDistance: 12000, minimumSpawnDistance: 10600, lateralSpacing: 700, entry: 'scramble',
        },
      },
      {
        id: 'flank-pressure', labelKey: 'mission.variant.support.flankPressure', weight: 1,
        changes: {
          hostiles: 2,
          hostileComposition: ['mig29', 'su27'],
          hostileEntry: 'scramble',
          groundPairs: 10,
          groundTrucks: 14,
          groundIto90Count: 1,
          groundShilkaCount: 3,
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'destroy-logistics', type: 'destroyOptionalGroundTarget', target: {
              collection: 'groundHostiles', role: 'logistics',
              labelKey: 'mission.optionalTarget.hostileLogistics',
            } },
            { id: 'protect-friendly', type: 'protectFriendlyGroundUnit', target: {
              collection: 'friendlyGround', role: 'defender',
              labelKey: 'mission.optionalTarget.friendlyArmor',
            } },
            { id: 'missile-reserve', type: 'preserveMissiles', minimumRemaining: 10 },
          ],
        },
        reinforcement: {
          probability: .2, delaySeconds: 72, hostiles: 1, composition: ['su27'],
          spawnDistance: 12000, minimumSpawnDistance: 10600, lateralSpacing: 700, entry: 'scramble',
        },
      },
    ],
  },
  training: {
    id: 'training',
    unlocks: [],
    deferredHostiles: true,
    navigationDistance: 7200,
    navigationRadius: 850,
    departureDuration: 3,
    hostiles: 0,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    objective: { type: 'training', duration: 90 },
    optionalObjectives: [
      { id: 'wingmen-home', type: 'allWingmenSurvive' },
      { id: 'no-damage', type: 'noDamage' },
      { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 180 },
    ],
    variants: [
      {
        id: 'standard-course', labelKey: 'mission.variant.training.standard', weight: 3,
        changes: {},
      },
      {
        id: 'extended-course', labelKey: 'mission.variant.training.extended', weight: 1,
        changes: {
          objective: { type: 'training', duration: 110 },
          navigationDistance: 6800,
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'no-damage', type: 'noDamage' },
            { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 210 },
          ],
        },
      },
    ],
  },
};
