function enemyReinforcementEncounter(probability, { support = false } = {}) {
  return {
    id: 'enemy-reinforcement',
    probability,
    trigger: {
      primaryGroupRemainingAtMost: 1,
      objectiveActive: true,
      playerCombatCapable: true,
      ...(support ? {
        primaryGroundRemainingAtLeast: 1,
        reinforcementLogisticsRemainingAtLeast: 1,
      } : {}),
    },
    delayRangeSeconds: { min: 12, max: 20 },
    warningEvent: 'encounter.reinforcementExpected',
    responses: [
      {
        id: 'north-pair', weight: 2, hostiles: 2,
        composition: ['mig29'], hostileRoles: ['sweep', 'sweep'], bearingDegrees: 0,
        spawnDistance: 12000, minimumSpawnDistance: 10600, lateralSpacing: 700, entry: 'scramble',
      },
      {
        id: 'wingman-pressure', weight: 1, hostiles: 2,
        composition: ['mig29'], hostileRoles: ['sweep', 'sweep'], targetPreference: 'wingmen',
        bearingDegrees: 270, spawnDistance: 12000, minimumSpawnDistance: 10600,
        lateralSpacing: 700, entry: 'scramble',
      },
      {
        id: 'strike-flight', weight: 1, hostiles: 2,
        composition: ['su27'], hostileRoles: ['strike', 'strike'], bearingDegrees: 90,
        spawnDistance: 12000, minimumSpawnDistance: 10600, lateralSpacing: 700, entry: 'scramble',
      },
    ],
  };
}

export const MISSIONS = {
  intercept: {
    id: 'intercept',
    unlocks: ['support'],
    deferredHostiles: true,
    navigationDistance: 5000,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 4,
    hostileSpawnDistance: 15500,
    hostileMinimumSpawnDistance: 14000,
    hostileStagingDistance: 6500,
    hostileLateralSpacing: 1250,
    openingDelay: 16,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    groundIto90Count: 0,
    groundShilkaCount: 0,
    objective: { type: 'clearAir' },
    optionalObjectives: [
      { id: 'wingmen-home', type: 'allWingmenSurvive' },
      { id: 'lead-intercept', type: 'interceptBeforeZone', target: {
        collection: 'airHostiles', index: 2, labelKey: 'mission.optionalTarget.strikeAircraft',
      }, zoneRadius: 7200 },
      { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 300 },
    ],
    variants: [
      {
        id: 'long-range-screen', labelKey: 'mission.variant.intercept.longRange', weight: 3,
        changes: {
          hostileComposition: ['mig29', 'mig29', 'su27', 'su27'],
          hostileRoles: ['sweep', 'sweep', 'strike', 'strike'],
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'lead-intercept', type: 'interceptBeforeZone', target: {
              collection: 'airHostiles', index: 2, labelKey: 'mission.optionalTarget.strikeAircraft',
            }, zoneRadius: 7200 },
            { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 300 },
          ],
        },
        encounters: [enemyReinforcementEncounter(.12)],
      },
      {
        id: 'rapid-scramble', labelKey: 'mission.variant.intercept.rapidScramble', weight: 1,
        changes: {
          hostiles: 5,
          hostileComposition: ['mig29', 'mig29', 'su27', 'su27', 'mig29'],
          hostileRoles: ['sweep', 'sweep', 'strike', 'strike', 'sweep'],
          hostileSpawnDistance: 13200,
          hostileMinimumSpawnDistance: 11800,
          hostileLateralSpacing: 1500,
          hostileEntry: 'scramble',
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'lead-intercept', type: 'interceptBeforeZone', target: {
              collection: 'airHostiles', index: 2, labelKey: 'mission.optionalTarget.strikeAircraft',
            }, zoneRadius: 7600 },
            { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 330 },
          ],
        },
        encounters: [enemyReinforcementEncounter(.24)],
      },
    ],
  },
  patrol: {
    id: 'patrol',
    unlocks: ['intercept'],
    deferredHostiles: true,
    navigationDistance: 5000,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 2,
    hostileSpawnDistance: 15500,
    hostileMinimumSpawnDistance: 14000,
    hostileStagingDistance: 6500,
    hostileLateralSpacing: 1450,
    openingDelay: 24,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    objective: { type: 'clearAir' },
    optionalObjectives: [
      { id: 'wingmen-home', type: 'allWingmenSurvive' },
      { id: 'no-damage', type: 'noDamage' },
      { id: 'missile-reserve', type: 'preserveMissiles', minimumRemaining: 16 },
    ],
    variants: [
      {
        id: 'routine-patrol', labelKey: 'mission.variant.patrol.routine', weight: 3,
        changes: { hostileComposition: ['su27', 'mig29'] },
        encounters: [enemyReinforcementEncounter(.18)],
      },
      {
        id: 'border-scramble', labelKey: 'mission.variant.patrol.borderScramble', weight: 1,
        changes: {
          hostiles: 3,
          hostileComposition: ['mig29', 'su27', 'mig29'],
          hostileSpawnDistance: 14000,
          hostileMinimumSpawnDistance: 12500,
          hostileLateralSpacing: 1750,
          hostileEntry: 'scramble',
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'no-damage', type: 'noDamage' },
            { id: 'missile-reserve', type: 'preserveMissiles', minimumRemaining: 15 },
          ],
        },
        encounters: [enemyReinforcementEncounter(.22)],
      },
    ],
  },
  support: {
    id: 'support',
    unlocks: [],
    wingmanInitialOrder: 'regroup',
    deferredHostiles: true,
    navigationDistance: 5000,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 1,
    hostileSpawnDistance: 15500,
    hostileMinimumSpawnDistance: 14000,
    hostileStagingDistance: 6500,
    openingDelay: 19,
    wingmen: 2,
    groundBattle: true,
    groundPairs: 9,
    groundTrucks: 16,
    groundFriendlyTrucks: 6,
    groundFrontSpan: 27000,
    convoyArea: 24000,
    hostileHelicopters: 2,
    hostileHelicopterSpawnDistance: 13000,
    hostileHelicopterMinimumSpawnDistance: 11000,
    hostileHelicopterLateralSpacing: 1400,
    hostileHelicopterSpawnAltitude: 520,
    groundIto90Count: 2,
    groundShilkaCount: 2,
    battlefieldIngressOffset: 5000,
    objective: { type: 'support' },
    optionalObjectives: [
      { id: 'wingmen-home', type: 'allWingmenSurvive' },
      { id: 'destroy-logistics', type: 'destroyOptionalGroundTarget', target: {
        collection: 'groundHostiles', role: 'logistics', index: 0,
        labelKey: 'mission.optionalTarget.reinforcementLogistics',
      } },
      { id: 'protect-friendly', type: 'protectFriendlyGroundUnit', target: {
        collection: 'friendlyGround', role: 'defender',
        labelKey: 'mission.optionalTarget.friendlyArmor',
      } },
      { id: 'missile-reserve', type: 'preserveMissiles', minimumRemaining: 12 },
    ],
    variants: [
      {
        id: 'armored-push', labelKey: 'mission.variant.support.armoredPush', weight: 3,
        changes: {},
        encounters: [enemyReinforcementEncounter(1, { support: true })],
      },
      {
        id: 'flank-pressure', labelKey: 'mission.variant.support.flankPressure', weight: 1,
        changes: {
          hostiles: 2,
          hostileComposition: ['mig29', 'su27'],
          hostileEntry: 'scramble',
          groundPairs: 10,
          groundTrucks: 14,
          groundIto90Count: 1,
          groundShilkaCount: 3,
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'destroy-logistics', type: 'destroyOptionalGroundTarget', target: {
              collection: 'groundHostiles', role: 'logistics', index: 0,
              labelKey: 'mission.optionalTarget.reinforcementLogistics',
            } },
            { id: 'protect-friendly', type: 'protectFriendlyGroundUnit', target: {
              collection: 'friendlyGround', role: 'defender',
              labelKey: 'mission.optionalTarget.friendlyArmor',
            } },
            { id: 'missile-reserve', type: 'preserveMissiles', minimumRemaining: 10 },
          ],
        },
        encounters: [enemyReinforcementEncounter(1, { support: true })],
      },
    ],
  },
  training: {
    id: 'training',
    unlocks: [],
    deferredHostiles: true,
    navigationDistance: 7200,
    navigationRadius: 850,
    departureDuration: 3,
    hostiles: 0,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    objective: { type: 'training', duration: 90 },
    optionalObjectives: [
      { id: 'wingmen-home', type: 'allWingmenSurvive' },
      { id: 'no-damage', type: 'noDamage' },
      { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 180 },
    ],
    variants: [
      {
        id: 'standard-course', labelKey: 'mission.variant.training.standard', weight: 3,
        changes: {},
      },
      {
        id: 'extended-course', labelKey: 'mission.variant.training.extended', weight: 1,
        changes: {
          objective: { type: 'training', duration: 110 },
          navigationDistance: 6800,
          optionalObjectives: [
            { id: 'wingmen-home', type: 'allWingmenSurvive' },
            { id: 'no-damage', type: 'noDamage' },
            { id: 'time-limit', type: 'completeBeforeTime', limitSeconds: 210 },
          ],
        },
      },
    ],
  },
};
