export const MISSIONS = {
  intercept: {
    id: 'intercept',
    unlocks: ['support'],
    deferredHostiles: true,
    navigationDistance: 8000,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 4,
    hostileSpawnDistance: 12000,
    hostileLateralSpacing: 1250,
    openingDelay: 16,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    groundIto90Count: 0,
    groundShilkaCount: 0,
    objective: { type: 'clearAir' },
  },
  patrol: {
    id: 'patrol',
    unlocks: ['intercept'],
    deferredHostiles: true,
    navigationDistance: 8500,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 2,
    hostileSpawnDistance: 12000,
    hostileLateralSpacing: 1450,
    openingDelay: 24,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    objective: { type: 'clearAir' },
  },
  support: {
    id: 'support',
    unlocks: [],
    deferredHostiles: true,
    navigationDistance: 7600,
    navigationRadius: 850,
    ingressAltitudeAgl: 900,
    departureDuration: 4,
    hostiles: 1,
    hostileSpawnDistance: 11500,
    openingDelay: 19,
    wingmen: 2,
    groundBattle: true,
    groundPairs: 9,
    groundTrucks: 16,
    groundFriendlyTrucks: 6,
    groundFrontSpan: 25000,
    convoyArea: 22000,
    hostileHelicopters: 2,
    hostileHelicopterSpawnDistance: 9500,
    hostileHelicopterLateralSpacing: 1400,
    hostileHelicopterSpawnAltitude: 520,
    groundIto90Count: 2,
    groundShilkaCount: 2,
    objective: { type: 'support' },
  },
  training: {
    id: 'training',
    unlocks: [],
    deferredHostiles: true,
    navigationDistance: 7200,
    navigationRadius: 850,
    departureDuration: 3,
    hostiles: 0,
    wingmen: 2,
    groundBattle: false,
    groundPairs: 0,
    groundTrucks: 0,
    groundFrontSpan: 0,
    convoyArea: 0,
    objective: { type: 'training', duration: 90 },
  },
};
